<img src='https://th.bing.com/th/id/OIP.0mtPy_tJkhR2cw2LACoGBwHaEK?pid=ImgDet&rs=1'>

In [ ]:
'''NumPy is a Python Library. It stands for 'Numerical Python'. 
It is a library consisting of multidimensional array objects.
'''


 # Numpy vs List
'''
Python List:

1.Able to store different data types in the same list.
2.Storing each item in random location in the memory.
3.Good for the scenario where list can grow dynamically.
4.Inbuilt data type.
5.It has more inbuilt functions.

NumPy Array:

1.Can store only one data type in an array at any time.
2.Storing each item is sequential which makes array more effective in processing.
3.Good for the scenario where the items are fixed size and same data time.
4.Need to install external library NumPy.
5.No extra functions, so it will not more memory store.
'''
 




<img src="https://res.cloudinary.com/hmqtkdlno/image/upload/v1592596177/utzc1ntfyu0modaxbzte.png">

<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png">

In [3]:
# for installing the numpy 
!pip install numpy

#import numpy module with alias np
import numpy as np

In [5]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a = np.array([1,2,3,4,'a'])

In [7]:
# print a
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

## Dimensions in Arrays


Numpy array can be of n dimentions

Lets create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

<p style='text-align: right;'> 3 points </p>


In [ ]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimension? Use ndim attribute on each variable to check its dimension

In [ ]:
#print dimentions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)



Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print(c.dtype)
print(d.dtype)

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [ ]:
#print type of a and b variable
print(type(a))
print(type(b))

In [ ]:
# Lets check length of array b, using len() function
len(d)

### Creating Numpy array


There are multiple ways to create numpy array. Lets walk over them

1. Using arrange() function <br>
<p style='text-align: right;'> 8 points </p>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
np.arange(1, 11)

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameters
np.arange(1,11,2)



2. Using eye Function <br>


In [ ]:
# create numpy array using eye function with 3 as passed parameter
np.eye(2, dtype = float) 

Wohoo! eye return a 2-D array with ones on the diagonal and zeros elsewhere.

3. Using zero function<br>


In [ ]:
#create a numpy array using zero function with (3,2) as passed parameter takes default float
np.zeros((3, 5),dtype='int') # default float

Zero function returns a new array of given shape and type, filled with zeros.

4. Using ones Function <br>


In [ ]:
#create a numpy array using ones function with (3,2) as passed parameter
np.ones((3, 2))

You noticed! ones function returns a new array of given shape and type, filled with ones.

5. Using full Function<br>


In [ ]:
#create a numpy array using full function with (3,2) and 2 as passed parameter
np.full((2, 3), 111,dtype=int)

<img src="https://backtobazics.com/wp-content/uploads/2018/08/numpy-eye-full-methods.jpg">



6. Using diag function<br>


In [ ]:
#create a numpy array using diag function passing a list [1,2,3,4,5]
x = [1,2,3,4,5,6,7]
np.diag(x)



## Numpy Reshape



Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

<p style='text-align: right;'> 6 points </p>


<img src="https://backtobazics.com/wp-content/uploads/2018/08/numpy-reshape-examples.jpg">

In [9]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [11]:
# Reshape x with 2 rows and 8 columns
n=x.reshape((8,2)) # 1d
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [13]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [15]:
# convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ravel-function-image-1.png">

In [ ]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
print(x)
x.reshape((2,8))

<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ndarray-flatten-function-image-1.png">

## NumPy Array Indexing


Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

<p style='text-align: right;'> 4 points </p>


In [ ]:
# Flattening x convert array into one dimensional
x.flatten()

In [17]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [19]:
# Get third element in array a
a[2]

6

In [ ]:
#Print 3rd, 5th, and 7th element in array a
a[0:7:2]

Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
# print the 3rd element from the 3rd row of a
a[2,2]

<img src="https://qph.fs.quoracdn.net/main-qimg-82a0721a240faf8b7aa563492f4ccadf">

In [21]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[1][1][2]

12

Great job! 
So now you have learned how to to indexing on various dimentions of numpy array.

## NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

    1. We pass slice instead of index like this: [start:end].
    2. We can also define the step, like this: [start:end:step].
    3. If we don't pass start its considered 0
    4. If we don't pass end its considered length of array in that dimension
    5. If we don't pass step its considered 1
    
<p style='text-align: right;'> 5 points </p>

    
1. **Array slicing in 1-D array.**

In [ ]:
arr=np.arange(1,11)
arr

In [ ]:
# Slice elements from 1st to 5th element from array arr:
arr[0:5]


In [ ]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

In [ ]:
# Slice elements from the beginning to index 5 (not included) in array arr:
arr[0:5]

In [ ]:
# Print every other element from index 1 to index 7:
arr[1:7:2]

In [ ]:
# Return every other element from the entire array arr:
arr[0:10:2]

In [ ]:
# Print array a
a

In [ ]:
# In array 'a' print index 2 from all the rows :
arr[2]

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[0:,1:]

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view



<p style='text-align: right;'> 7 points </p>


In [25]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# assign x2 = x1
x2 = x1 # view 

In [31]:
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Ok now you have seen that both of them are same 

In [ ]:
# change 1st element of x2 as 10
x2[0] = 10

In [ ]:
#Again print x1 and x2
print(x1)
print(x2)

In [33]:
print(id(x1))
print(id(x2))

2463409680720
2463409680720


Wait a minute. Just check your above result on change of x2, x1 also got changed. Why?

Lets check if both the variables shares memory. Use numpy shares_memory() function to check if both x1 and x2 shares a  memory.


In [35]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
2463409680720
2463409680720


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [43]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [41]:
# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

True

In [ ]:
#Change 1st element of x3=100
x3[0] = 100

In [ ]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

x4 = np.copy(x1)

In [ ]:
# Change the last element of x4 as 900
x4[-1] = 900

In [57]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[0 1 2 3 4 5 6 7 8 9]


NameError: name 'x4' is not defined

Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.



In [ ]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)

You see! x1 and x4 don't share its memory. 

So with all our outputs we can takeaway few points:

    1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

    2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

    3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## More operations on Numpy

**1. Applying conditions**



<p style='text-align: right;'> 5 points </p>


In [ ]:
#print a
a

We are going to use 'a' array for all our array condition operations.


In [45]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 3


array([False,  True,  True,  True,  True,  True,  True,  True])

In [47]:
# Get a list with all elements of array 'a' grater than 3
a[a > 3]

array([ 4,  6,  8, 10, 12, 14, 16])

In [49]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 3) & (a < 6)]

array([4])

In [51]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1 == x4
# print(x1)
# print(x4)

NameError: name 'x4' is not defined

You can see in above output that the last element is not same in both x1 and x4

Well done so far.

Lets check how to transpose an array

**2. Transposing array**


In [53]:
# Print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("-----------------")
print(a) 

[ 2  4  6  8 10 12 14 16]
-----------------
[ 2  4  6  8 10 12 14 16]


In above output all the rows became columns by transposing 

**3. hstack vs vstack function**



Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns


<img src="https://images4.pianshen.com/908/91/91b34f7c4a78a2e22d6b7ba0a7186584.png">

In [55]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[0 1 2 3 4 5 6 7 8 9]


NameError: name 'x4' is not defined

In [59]:
#stack x1 and x4 along rows
np.hstack((x1, x4))

NameError: name 'x4' is not defined

## Adding, Insert and delete Numpy array


<p style='text-align: right;'> 3 points </p>


Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2
print(x2)
np.delete(x2, 0)

Did you see? 2 value is deleted from x2 which was at index position 2

## Mathmatical operations on Numpy array



<p style='text-align: right;'> 8 points </p>


In [ ]:
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# print trigonometric sin value of each element of a
np.sin(a)

In [ ]:
(np.sin(a))/(np.cos(a))

In [ ]:
# print trigonometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

In [ ]:
# Print exponential value of each elements of a
np.exp(a)

In [ ]:
# print total sum of elements of a
np.sum(a)

In [61]:
# Print sum in array a column wise
np.sum(a, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# Print sum in array a row wise
np.sum(a, axis=0)

<img src="https://th.bing.com/th/id/R.9230ced1c11e813fb069ddcac6566fdf?rik=C1ohvKa4zik%2b4w&riu=http%3a%2f%2flh5.ggpht.com%2f-1oz5Rz51kmo%2fU_xUcCLo4KI%2fAAAAAAAAB1g%2fyzk9KPcJ-NM%2fmeasures%25252520of%25252520central%25252520tendency_thumb%2525255B13%2525255D.gif%3fimgmax%3d800&ehk=%2bBH1cRV14pqT3nEfMTOkYImdkFZDlqR6fFJ1eM%2bKAcw%3d&risl=&pid=ImgRaw&r=0">

In [ ]:
# print median of array a
np.median(a)

In [ ]:
# print mean of array a
np.mean(a)


<img src="https://th.bing.com/th/id/R.a2c52d7062fa0de9d9df6032b7e0da75?rik=ptW1AfWGEGJi%2fQ&riu=http%3a%2f%2fimage.slideserve.com%2f274561%2fformula-for-standard-deviation-l.jpg&ehk=VClOXZLFkcG6HPqdc7rRMwWSMjYJ2T%2fGN1A8smQgV5Q%3d&risl=&pid=ImgRaw&r=0">

In [ ]:
# print standard deviation of array a
np.std(a)

In [ ]:
#print largest element present in array a
np.max(a)

In [ ]:
# print sorted x4 array
np.sort(x4)

## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

<p style='text-align: right;'> 4 points </p>


In [ ]:
# print the indexes where the value is 4 in array x1

m=np.where(x1 == 4)
m

In [ ]:
#print array x1
x1

In [ ]:
c=np.array([44,55,66,88,99,12,12,12,12,12,10,10,10,101,0])

In [ ]:
# Print the indexes where the values are even in array x1
np.where(c%2 == 0)


In [ ]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0

np.where(x1>5, x1, 0)

In [63]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [65]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']
